### ISSUE TITLE
Profile is not updating

### ISSUE THREAD

**Issue by iayushanand** [devbio-me/issues#5]
Whenever I try to Save changes, the profile gets saved but not updated

![Save Changes](https://user-images.githubusercontent.com/77532758/117096600-3d907680-ad87-11eb-9036-7652487ca469.JPG)
![Not Updated](https://user-images.githubusercontent.com/77532758/117096597-3c5f4980-ad87-11eb-895e-35631696aa3d.JPG)

**Comment by CodeWithSwastik** [comment]
This will be fixed soon, apparently the modal always shows "Profile Updated"

**Comment by FalseDev** [comment]
I'm closing this issues since it has been resolved.

**Comment by CodeWithSwastik** [comment]
Reopening this issue since its not been fixed yet

**Comment by CodeWithSwastik** [comment]
This has been fixed now
